version: "3.9"
services:
  db:
    image: postgres:15
    container_name: fintrack-db
    restart: always
    environment:
      POSTGRES_USER: fintrack_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fintrack_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: fintrack-api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://fintrack_user:password123@db:5432/fintrack_db
      SECRET_KEY: apisederhana
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
